# Generated by Django 2.1.3 on 2019-01-19 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import users.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', enumfields.fields.EnumField(default=1, enum=users.enums.Measurement, max_length=10)),
                ('height', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
