version: '3'

services:
    db:
        image: postgres:alpine
        volumes:
            - postgres_fittrack:/tmp/pgdata
        ports:
            - "5432:5432"
    fittrack:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
            - caching
        healthcheck:
            test: ["CMD", "curl", "-f", "http://db:5432"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: on-failure:3
        env_file:
            - ./container.env
        command: ["./entrypoint.sh", "python", "./manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - .:/usr/src/fittrack
        ports:
            - "8000:8000"
        links:
            - db
            - caching
    pgadmin:
        image: fenglc/pgadmin4
        ports:
            - "5050:5050"
        volumes:
            - pgadmin:/root/.pgadmin
        links:
            - db
    caching:
        image: redis:5-alpine
        ports:
            - "6379:6379"
volumes:
    postgres_fittrack:
    pgadmin:

